### ISSUE TITLE
anyRequire not working

### ISSUE THREAD

**Issue by trasanthanh** [ajv-validator/ajv-keywords#112]
I was validated with option "anyRequire" in my project but it not working . 
this is my schema :
var schema = { 
    "type": "object",
    "properties": {
        "second" : { "type" : "number", "maximum": 59, "minimum": 0 },
        "minute" : { "type" : "number", "maximum": 59, "minimum": 0 },
    },
    "anyRequired": ["second", "minute"]   
}; 
- with input : empty object such as : {} it return true

**Comment by epoberezkin** [comment]
Please provide the full code sample, ideally via runkit.com - it is not clear what is not working and why.

**Comment by epoberezkin** [comment]
Closing it, please re-open with the code sample if the issue persist. Thank you.
