### ISSUE TITLE
ajv transform and validate [string type schema]

### ISSUE THREAD

**Issue by cyb3rs4pi3n** [ajv-validator/ajv-keywords#126]
example : { type: 'string', transform: ['trim'], minLength: 1, maxLength: 255 }

this seems to be returning the transformed string however fails to validate the conditions following it. couldn't find resources to handle this particular case. Is the behaviour intended?

**Comment by epoberezkin** [comment]
Difficult to say what is the issue without the full code sample - can you post it? (ideally to run kit)

**Comment by cyb3rs4pi3n** [comment]
{ type: 'string', allOf: [{ transform: ['trim'] }, { minLength: 1, maxLength: 255 }] }

solved using the above schema
