### ISSUE TITLE
No declaration file in npm package causing TypeScript error

### ISSUE THREAD

**Issue by eytienne** [ajv-validator/ajv-keywords#134]
I've this in vscode :
```
File '.../node_modules/ajv-keywords/ajv-keywords.d.ts' not found.
```
Maybe the declaration file is not packed to npm ?

_Originally posted by @eytienne in https://github.com/ajv-validator/ajv-keywords/issues/53#issuecomment-663752265_

**Comment by mercutiodesign** [comment]
I found the problem and fixed it in #131, let's hope they merge it soon.

**Comment by epoberezkin** [comment]
Yes - it’s exactly the problem. Previously types were in @types/Ajv-keywords, now they were moved there but missed in files... Thanks.

**Comment by epoberezkin** [comment]
in 3.5.2
