### ISSUE TITLE
Support Date objects in formatMinimum, formatMaximum keywords

### ISSUE THREAD

**Issue by NemeSnz** [ajv-validator/ajv-keywords#135]
**What version of Ajv you are you using?**
 "ajv": "6.12.4",
 "ajv-keywords": "3.5.2"

**What problem do you want to solve?**
I want to define a JSON Schema where a Date property is before another Date property. Both properties are instances of Date.
```
{
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: {
    someDate: {
      type: 'object',
      instanceof: 'Date',
      format: 'date',
      formatMaximum: {
        $data: '1/anotherDate',
      },
    },
    anotherDate: {
      type: 'object',
      instanceof: 'Date',
      format: 'date',
      formatMinimum: {
        $data: '1/someDate',
      },
    },
  },
};

```

**What do you think is the correct solution to problem?**
Adding support for Date objects in formatMinimum, formatMaximum keywords.

- Change `KeywordDefinition.type` from `type: 'string'` to `type: ['string', 'object']`.
- Since "date" format is already being extended with a compare function that uses `>`, `<`, `===` available to Date instances, there is no need to write more code.

**Will you be able to implement it?**
If there are no further considerations, I can implement this.

**Comment by epoberezkin** [comment]
I need to think about it, but it is most likely won't be possible - format only supports strings and numbers... It is best to define custom keywords for this purpose or process in the application code...

**Comment by NemeSnz** [comment]
I've also concluded that it would be best to simply use strings for storing dates.
