### ISSUE TITLE
Add ability to pass keywords in the AJV options during creation of the instance.

### ISSUE THREAD

**Issue by dietergeerts** [ajv-validator/ajv-keywords#136]
Maybe I'm overlooking something in the docs, but I can't seem to find a way to add keywords with the `keywords` option you can pass to create an AJV instance. This would simplify the process of creating an instance.

My use-case is as follows:
- We have a package for all our models, with schemas included. So we know which keywords we need to add.
- There are several packages that will use these models, BUT they don't all use the same configuration.
- So each of these packages will create their own instance, importing a configuration from the model package, based on their needs. _(we have several configs to pick from)_

With this, and the installation of this package, we currently need to add an extra step: a function that can be executed to add all keywords.

If this package could allow adding keywords through the configuration, we could simply add them to our pre-defined configs.

**Comment by epoberezkin** [comment]
This option already exists - just was not added to the list of all options (needs to be added in v7 too)

https://github.com/ajv-validator/ajv/pull/1137/files

**Comment by dietergeerts** [comment]
@epoberezkin , but how can this be used with "ajv-keywords" package? as those are defined as functions where you need to pass the ajv instance. My request is to pass these "ajv-keywords" in the options when creating the instance.

**Comment by epoberezkin** [comment]
It needs to be documented indeed.

In ajv v6 you can:

```javascript
const ajv = new Ajv({keywords: {
   instanceof: require("ajv-keywords/keywords/instanceof").definition,
   // ...
}})
```

In ajv v7 (once ajv-keywords is updated to work with v7, which is next week's ambitious goal) you will be able to:

```javascript
const ajv = new Ajv({keywords: [
   require("ajv-keywords/keywords/instanceof").definition,
   // ...
]})
```

The first is a bit clumsy (this option format is deprecated in v7), but the second is better - I am not sure it is a good idea to add all of them including those you don't use.

I will think whether to expose definitions with some shorter imports, so we could use, e.g., require("ajv-keywords/definitions/instanceof"), and maybe even `require("ajv-keywords/definitions")` to pass all of them to the option.

**Comment by epoberezkin** [comment]
actually this is not so simple.

Currently to get definitions you actually need to call the plugin first, not even sure what was the point of adding it...

So above won't work.

The problem is that several keywords depend on ajv instance settings, so currently the instance passed to plugin is also used to get these settings. So to make definitions available separately would require passing the settings they need - which may be a good thing to do anyway.

**Comment by epoberezkin** [comment]
it's done in v4 beta
