### ISSUE TITLE
how to detect if property value is  "NA" or "undefined"  and throw error?

### ISSUE THREAD

**Issue by lmk07** [ajv-validator/ajv-keywords#151]
Hi guys,
            i just want to know, how to throw error if my property value is "NA" or "undefined".
            
            sample data:
                              `"data":{
                                          "fname":"NA",
                                          "lname":"undefined",
                                          "age":"28" 
                                }`

            now i want to show error for fname and lname property

**Comment by epoberezkin** [comment]
https://github.com/ajv-validator/ajv/issues/1395
