### ISSUE TITLE
Pattern keyword not working properly.

### ISSUE THREAD

**Issue by PParshive** [ajv-validator/ajv-keywords#160]
Hi,

In my code pattern "[a-z A-Z _ 0-9\\-\\.]+" is match with " xyz/" string. Here, "xyz" present in pattern but "/" is not present in pattern, so its should be display validation error. I am facing problem here.

My schema :
"folderName": {
"$id": "#root/ruleMetadata/folderName", 
"title": "Foldername", 
"type": "string",
"default": "",
"examples": [
"sprint1"
],
"pattern": "[a-z A-Z _ 0-9\\-\\.]+"
},

Actual Result: While entering "xyz/" in folderName then validation error not get. Its seem like pattern is match with string, but "/" is not present in pattern.

Excepted Result : Its should be display validation error : 

dataPath: "/ruleMetadata/folderName"
keyword: "pattern"
message: "should match pattern "[a-z A-Z _ 0-9\-\.]+""
params: {pattern: "[a-z A-Z _ 0-9\-\.]+"}
schemaPath: "#/properties/ruleMetadata/properties/folderName/pattern"

Please help me to solve the problem as soon as possible.

Thanks!

**Comment by epoberezkin** [comment]
the pattern should be anchored to the beginning/end of string (with ^ and $) to match the entire string, as is it matches the fragment - it's the same syntax as JS regexp.
