### ISSUE TITLE
Does ajv-keywords work with ajv/dist/jtd?

### ISSUE THREAD

**Issue by jrr** [ajv-validator/ajv-keywords#166]
For JTD's "timestamp" type, AJV will [currently accept](https://ajv.js.org/json-type-definition.html#type-form) either a Date object or a correctly-formatted string.

For my use case (which doesn't demand portability) I want to restrict this to just Date objects. This seems like a perfect fit for the [instanceof keyword](https://github.com/ajv-validator/ajv-keywords#instanceof).

When I try to connect ajv-keywords to ajv-in-JTD-mode, though, I'm getting an error:

```
    schema is invalid: data/anyOf must NOT have additional properties, data must have property 'ref', data must have property 'type', data must have property 'enum', data must have property 'elements', data must have property 'properties', data must have property 'optionalProperties', data must have property 'discriminator', data must have property 'values', data must match a schema in union

      2 | import instanceOfKeyword from "ajv-keywords/dist/definitions/instanceof";
      3 | import Ajv, { JTDSchemaType } from "ajv/dist/jtd";
    > 4 | const ajv = new Ajv({ keywords: [instanceOfKeyword()] });
        |             ^
      5 |
      6 | type OkayT<T> = {
      7 |   outcome: "OK";

      at Ajv.validateSchema (node_modules/ajv/lib/core.ts:473:18)
      at Ajv._addSchema (node_modules/ajv/lib/core.ts:673:30)
      at Ajv.compile (node_modules/ajv/lib/core.ts:341:22)
      at Ajv.keywordMetaschema (node_modules/ajv/lib/core.ts:830:29)
      at Ajv.addKeyword (node_modules/ajv/lib/core.ts:563:23)
      at Ajv.addVocabulary (node_modules/ajv/lib/core.ts:533:41)
      at Ajv.addInitialKeywords (node_modules/ajv/lib/core.ts:745:10)
      at new Ajv (node_modules/ajv/lib/core.ts:285:43)
      at new Ajv (node_modules/ajv/lib/jtd.ts:40:5)
      at Object.<anonymous> (src/foo/validation/schema-validation.ts:4:13)
```

Here's a [runkit repro](https://runkit.com/jrr/ajv-jtd-instanceof).

Two questions:
1) Is ajv-keywords instanceof the best way to restrict JTD timestamps to Date objects?
2) How do I connect ajv-keywords to ajv/dist/jtd? 

Versions:
- ajv 8.0.5
- ajv-keywords 5.0.0.

**Comment by epoberezkin** [comment]
The problem is that instanceof has a meta-schema that is not JTD schema: https://github.com/ajv-validator/ajv-keywords/blob/master/src/definitions/instanceof.ts#L48

It may work with some other keywords, that do not define any meta-schema. In this case you could fork/copy-paste just this keyword and use by removing/replacing meta-schema.

Also, note JTD schemas would only support additional keywords inside metadata member, as the spec requires, so your schema should be:

```javascript
const schema = {
  type: "timestamp",
  metadata: {
    instanceof: "Date"
  }
}
```

see here: https://ajv.js.org/json-type-definition.html#metadata-schema-member

**Comment by jrr** [comment]
Thanks! I got it working with a hand-written keyword:

```ts
export const isDateObject: KeywordDefinition = {
  keyword: "isDateObject",
  compile: () => {
    return (data) => typeof data == "object" && data instanceof Date;
  },
  error: {
    message: (_) => "expected Date type",
  },
};

ajv.addKeyword(isDateObject);

// example usage:
{ type: "timestamp", metadata: { isDateObject: true } }
```



Next question (perhaps this belongs in the other repo): is there a good way to apply that keyword to all timestamp fields globally, such that it doesn't have to be part of the input schema?

I'm still wrapping my head around concepts like _keyword_ and _metaschema_ and _vocabulary_, and hoping one of them can let me change the rules like this.

(for now I'm patching the schema on the way in, tacking metadata to all my timestamps, and hoping for a better approach ;) )

**Comment by epoberezkin** [comment]
No easy way to do it.

It can make sense to have an option that controls timestamp validation in JTD - to allow string, Date or both (default). It’s best to make a separate issue in Ajv repo.
