### ISSUE TITLE
transform: trim - Appears to be executed after validation?

### ISSUE THREAD

**Issue by carlnordenfelt** [ajv-validator/ajv-keywords#221]
I'm having issues combining trim with `minLength`.

```
"ajv": "6.12.6",
"ajv-keywords": "3.5.2"
```
I realize these are old versions and perhaps this has been addressed in never versions but I'd still not expect to find the issue I'm having.

The properties are trimmed but I would expect validation to fail:

```
const Ajv = require('ajv');
const AjvKeywords = require('ajv-keywords');

const ajv = new Ajv({ allErrors: true, useDefaults: true, coerceTypes: true, jsonPointers: true });
AjvKeywords(ajv, ['transform']);

const schema = {
    type: 'object',
    properties: {
        trimmed: {
            type: 'string',
            transform: ['trim'],
            minLength: 2,
        },
    },
};

const validate = ajv.compile(schema);

const data = { trimmed: 'd ' };
validate(data);

console.log(validate.errors); // null
console.log(data); // { trimmed: 'd' }

// Expected:
// console.log(validate.errors);
// [
//   {
//     keyword: 'minLength',
//     dataPath: '/trimmed',
//     schemaPath: '#/properties/trimmed/minLength',
//     params: { limit: 2 },
//     message: 'should NOT be shorter than 2 characters'
//   }
// ]
```

After trim `data.trimmed.length` will equal 1 and should fail on `minLength: 2`.
It works as expected if I, for example, set minLength to 3.

I have also tried different variations of `allOf` that I have seen suggested in other issues but to no avail:

```
const schema = {
    type: 'object',
    properties: {
        trimmed: {
            type: 'string',
            allOf: [
                { transform: ['trim'] }, 
                { minLength: 1 }
            ]
        },
    },
};
```

```
const schema = {
    type: 'object',
    properties: {
        trimmed: {
            type: 'string',
            allOf: [
                {
                    transform: ['trim'],
                    minLength: 1,
                },
            ],
        },
    },
};
```

I hope the issue is that I am using it wrong :)

**Comment by epoberezkin** [comment]
The order of keyword validation in a single schema object is determined by the order in which they are added to the instance, and transform being non-standard is added after minLenght. Inside allOf subschemas are validated in the order of the items, so with allOf it works.

Your first option with allOf is correct, it works, at least with the most recent versions: https://runkit.com/esp/619a9626a28a41000857b902

Either it indeed is broken in the older versions you use - please let me know if this is the case - or you've missed that it works correctly while testing various options.

**Comment by epoberezkin** [comment]
actually it works with the old versions too, closing.

Updated it here: https://runkit.com/esp/619a9626a28a41000857b902
