### ISSUE TITLE
In 3.5.2 version, I'm getting an error  Error: Cannot find module './keywords'

### ISSUE THREAD

**Issue by aswinvk28** [ajv-validator/ajv-keywords#224]
This is affecting webpack installations and many packages. 

In 3.5.2 version, I'm getting an error called 
 Error: Cannot find module './keywords'

Please resolve.

**Comment by epoberezkin** [comment]
Could you point to a specific example please (e.g. broken build?)

**Comment by epoberezkin** [comment]
Or a sample repo where it happens

**Comment by aswinvk28** [comment]
I could not replicate in my local machine, but when I checked the cloud version, the index.js was missing from it. I guess it is not the fault of the library. 
If I get to replicate this error, I will post an issue. 

The webpack is clearly working in my local machine. Thanks by the way.

**Comment by aswinvk28** [comment]
I was trying to install elyra
https://elyra.readthedocs.io/en/stable/getting_started/installation.html

In my local machine it is working. But the cloud faced with some issues of Javascript heap memory allocation.

**Comment by epoberezkin** [comment]
this is not the problem of the package then, closing...
